export const ActionTypes = {
    // 
    TOGGLE_SHOW_CUSTOMIZE_ORDER_MODAL: 'TOGGLE_SHOW_CUSTOMIZE_ORDER_MODAL',
    TOGGLE_SHOW_ORDER: 'TOGGLE_SHOW_ORDER',
    ADD_PIZZA_TO_ORDER: 'ADD_PIZZA_TO_ORDER',
    REMOVE_PIZZA_FROM_ORDER: 'REMOVE_PIZZA_FROM_ORDER',
    ANNUL_ORDER: 'ANNUL_ORDER',

    GET_PIZZA: 'GET_PIZZA',

    // pizzas
    GET_PIZZAS_REQUESTED: 'GET_PIZZAS_REQUESTED',
    GET_PIZZAS_SUCCESS: 'GET_PIZZAS_SUCCESS',
    GET_PIZZAS_FAILED: 'GET_PIZZAS_FAILED',

    // pizza
    GET_PIZZA_REQUESTED: 'GET_PIZZA_REQUESTED',
    GET_PIZZA_SUCCESS: 'GET_PIZZA_SUCCESS',
    GET_PIZZA_FAILED: 'GET_PIZZA_FAILED',

    // auth
    TOGGLE_SHOW_AUTH_MODAL: 'TOGGLE_SHOW_AUTH_MODAL'
}