export const ActionTypes = {
    // 
    TOGGLE_SHOW_CUSTOMIZE_ORDER_MODAL: 'TOGGLE_SHOW_CUSTOMIZE_ORDER_MODAL',
    TOGGLE_SHOW_ORDER: 'TOGGLE_SHOW_ORDER',
    ADD_PIZZA_TO_ORDER: 'ADD_PIZZA_TO_ORDER',
    REMOVE_PIZZA_FROM_ORDER: 'REMOVE_PIZZA_FROM_ORDER',

    GET_PIZZA: 'GET_PIZZA',


    // 
    GET_PIZZAS_REQUESTED: 'GET_PIZZAS_REQUESTED',
    GET_PIZZAS_SUCCESS: 'GET_PIZZAS_SUCCESS',
    GET_PIZZAS_FAILED: 'GET_PIZZAS_FAILED'
}